version: '3.5'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    volumes:
      - ./database/backup.bak:/var/opt/mssql/backup/backup.bak
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: SuperVfSoft1!
      MSSQL_PID: Developer
    ports:
      - 1434:1433

#  web:
#    image: nginx
#    ports:
#      - 8181:80
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

#  qisim:
#    build: ./qisim
#    ports:
#     - 8282:80
