version: '3.5'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: SuperVfSoft1!
      MSSQL_PID: Developer
    ports:
      - 1433:1433